name: emotion_reg
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - comm=0.2.3
  - debugpy=1.8.16
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.1
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=8.18.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - krb5=1.21.3
  - libcxx=20.1.8
  - libedit=3.1.20250104
  - libffi=3.4.4
  - libsodium=1.0.20
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.5.4
  - packaging=25.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.2
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - pyzmq=27.1.0
  - readline=8.3
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing_extensions=4.14.1
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - attrs==25.4.0
      - cffi==2.0.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - fst-pso==1.8.1
      - imagecorruptions-imaug==1.1.3
      - imageio==2.37.0
      - imaug==0.4.2
      - imbalanced-learn==0.12.3
      - imblearn==0.0
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - llvmlite==0.45.1
      - matplotlib==3.10.7
      - mediapipe==0.10.7
      - miniful==0.0.6
      - networkx==3.4.2
      - numba==0.62.1
      - numpy==1.26.4
      - opencv-contrib-python==4.8.1.78
      - opencv-python==4.8.1.78
      - opencv-python-headless==4.11.0.86
      - pandas==2.2.2
      - pillow==11.3.0
      - protobuf==3.20.3
      - pycparser==2.23
      - pyparsing==3.2.5
      - pytz==2025.2
      - pywavelets==1.8.0
      - scikit-image==0.21.0
      - scikit-learn==1.5.2
      - scipy==1.12.0
      - seaborn==0.13.2
      - shapely==2.1.2
      - simpful==2.12.0
      - sounddevice==0.5.2
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tqdm==4.67.1
      - tzdata==2025.2
