name: emotion
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scikit-image
  - imbalanced-learn
  - opencv
  - dlib
  - cmake
  - boost-cpp
  - jupyterlab
  - ipykernel
  - pip
  - vc14_runtime
  - ucrt
  - pip:
      - pyfume>=0.1.13
      - simpful>=2.12
      - anfis==0.3.1
      - tqdm>=4.64.1
      - notebook>=6.4.12
