# WARNING: this source code was automatically generated by pyFUME.
from simpful import *

FS = FuzzySystem(show_banner=False)
RULE1 = "IF (x1 IS cluster1) AND (x2 IS cluster1) AND (x3 IS cluster1) AND (x4 IS cluster1) AND (x5 IS cluster1) AND (x6 IS cluster1) AND (x7 IS cluster1) AND (x8 IS cluster1) THEN (OUTPUT IS fun1)"
RULE2 = "IF (x1 IS cluster2) AND (x2 IS cluster2) AND (x3 IS cluster2) AND (x4 IS cluster2) AND (x5 IS cluster2) AND (x6 IS cluster2) AND (x7 IS cluster2) AND (x8 IS cluster2) THEN (OUTPUT IS fun2)"
RULE3 = "IF (x1 IS cluster3) AND (x2 IS cluster3) AND (x3 IS cluster3) AND (x4 IS cluster3) AND (x5 IS cluster3) AND (x6 IS cluster3) AND (x7 IS cluster3) AND (x8 IS cluster3) THEN (OUTPUT IS fun3)"
RULE4 = "IF (x1 IS cluster4) AND (x2 IS cluster4) AND (x3 IS cluster4) AND (x4 IS cluster4) AND (x5 IS cluster4) AND (x6 IS cluster4) AND (x7 IS cluster4) AND (x8 IS cluster4) THEN (OUTPUT IS fun4)"
RULE5 = "IF (x1 IS cluster5) AND (x2 IS cluster5) AND (x3 IS cluster5) AND (x4 IS cluster5) AND (x5 IS cluster5) AND (x6 IS cluster5) AND (x7 IS cluster5) AND (x8 IS cluster5) THEN (OUTPUT IS fun5)"
RULE6 = "IF (x1 IS cluster6) AND (x2 IS cluster6) AND (x3 IS cluster6) AND (x4 IS cluster6) AND (x5 IS cluster6) AND (x6 IS cluster6) AND (x7 IS cluster6) AND (x8 IS cluster6) THEN (OUTPUT IS fun6)"
FS.add_rules([RULE1, RULE2, RULE3, RULE4, RULE5, RULE6])

FS.set_crisp_output_value('fun1', 3.001674)
FS.set_crisp_output_value('fun2', 3.001652)
FS.set_crisp_output_value('fun3', 3.001695)
FS.set_crisp_output_value('fun4', 3.001648)
FS.set_crisp_output_value('fun5', 3.001675)
FS.set_crisp_output_value('fun6', 3.001686)

FS_1 = FuzzySet(function=Gaussian_MF(-40.610087, 607.418983), term='cluster1')
FS_2 = FuzzySet(function=Gaussian_MF(48.031026, 664.116298), term='cluster2')
FS_3 = FuzzySet(function=Gaussian_MF(3.797635, 256.740236), term='cluster3')
FS_4 = FuzzySet(function=Gaussian_MF(44.333727, 550.880304), term='cluster4')
FS_5 = FuzzySet(function=Gaussian_MF(-1.958904, 255.597890), term='cluster5')
FS_6 = FuzzySet(function=Gaussian_MF(-34.972318, 475.916493), term='cluster6')
MF_x1 = LinguisticVariable([FS_1, FS_2, FS_3, FS_4, FS_5, FS_6], concept='x1' , universe_of_discourse=(-15.97575855255127, 17.191604614257812))
FS.add_linguistic_variable('x1', MF_x1)

FS_7 = FuzzySet(function=Gaussian_MF(-0.435355, 204.795184), term='cluster1')
FS_8 = FuzzySet(function=Gaussian_MF(0.088450, 208.810515), term='cluster2')
FS_9 = FuzzySet(function=Gaussian_MF(0.425778, 270.874564), term='cluster3')
FS_10 = FuzzySet(function=Gaussian_MF(0.143034, 181.378966), term='cluster4')
FS_11 = FuzzySet(function=Gaussian_MF(-1.249848, 301.904383), term='cluster5')
FS_12 = FuzzySet(function=Gaussian_MF(0.239796, 182.270039), term='cluster6')
MF_x2 = LinguisticVariable([FS_7, FS_8, FS_9, FS_10, FS_11, FS_12], concept='x2' , universe_of_discourse=(-19.386720657348633, 19.39734649658203))
FS.add_linguistic_variable('x2', MF_x2)

FS_13 = FuzzySet(function=Gaussian_MF(0.119348, 174.768882), term='cluster1')
FS_14 = FuzzySet(function=Gaussian_MF(0.696402, 175.288852), term='cluster2')
FS_15 = FuzzySet(function=Gaussian_MF(0.380672, 230.026097), term='cluster3')
FS_16 = FuzzySet(function=Gaussian_MF(0.549019, 151.040454), term='cluster4')
FS_17 = FuzzySet(function=Gaussian_MF(-0.109651, 269.437837), term='cluster5')
FS_18 = FuzzySet(function=Gaussian_MF(0.147335, 157.455416), term='cluster6')
MF_x3 = LinguisticVariable([FS_13, FS_14, FS_15, FS_16, FS_17, FS_18], concept='x3' , universe_of_discourse=(-15.655389785766602, 16.97960662841797))
FS.add_linguistic_variable('x3', MF_x3)

FS_19 = FuzzySet(function=Gaussian_MF(-0.528187, 179.275123), term='cluster1')
FS_20 = FuzzySet(function=Gaussian_MF(0.589471, 173.726289), term='cluster2')
FS_21 = FuzzySet(function=Gaussian_MF(-0.055879, 232.544409), term='cluster3')
FS_22 = FuzzySet(function=Gaussian_MF(0.320555, 157.695243), term='cluster4')
FS_23 = FuzzySet(function=Gaussian_MF(-0.701105, 271.074514), term='cluster5')
FS_24 = FuzzySet(function=Gaussian_MF(0.182376, 160.944701), term='cluster6')
MF_x4 = LinguisticVariable([FS_19, FS_20, FS_21, FS_22, FS_23, FS_24], concept='x4' , universe_of_discourse=(-16.518781661987305, 16.638397216796875))
FS.add_linguistic_variable('x4', MF_x4)

FS_25 = FuzzySet(function=Gaussian_MF(0.225588, 187.655562), term='cluster1')
FS_26 = FuzzySet(function=Gaussian_MF(1.353645, 178.723523), term='cluster2')
FS_27 = FuzzySet(function=Gaussian_MF(0.968311, 236.710070), term='cluster3')
FS_28 = FuzzySet(function=Gaussian_MF(1.168629, 154.470268), term='cluster4')
FS_29 = FuzzySet(function=Gaussian_MF(0.348087, 275.521816), term='cluster5')
FS_30 = FuzzySet(function=Gaussian_MF(0.676821, 164.727303), term='cluster6')
MF_x5 = LinguisticVariable([FS_25, FS_26, FS_27, FS_28, FS_29, FS_30], concept='x5' , universe_of_discourse=(-15.54614543914795, 17.924781799316406))
FS.add_linguistic_variable('x5', MF_x5)

FS_31 = FuzzySet(function=Gaussian_MF(0.048336, 154.521040), term='cluster1')
FS_32 = FuzzySet(function=Gaussian_MF(0.170422, 153.311181), term='cluster2')
FS_33 = FuzzySet(function=Gaussian_MF(0.239848, 206.483785), term='cluster3')
FS_34 = FuzzySet(function=Gaussian_MF(-0.024663, 135.713666), term='cluster4')
FS_35 = FuzzySet(function=Gaussian_MF(0.464738, 232.036181), term='cluster5')
FS_36 = FuzzySet(function=Gaussian_MF(0.062599, 135.400201), term='cluster6')
MF_x6 = LinguisticVariable([FS_31, FS_32, FS_33, FS_34, FS_35, FS_36], concept='x6' , universe_of_discourse=(-13.68603801727295, 14.10755443572998))
FS.add_linguistic_variable('x6', MF_x6)

FS_37 = FuzzySet(function=Gaussian_MF(-0.824638, 162.957984), term='cluster1')
FS_38 = FuzzySet(function=Gaussian_MF(-0.759092, 149.100225), term='cluster2')
FS_39 = FuzzySet(function=Gaussian_MF(-0.763486, 213.186782), term='cluster3')
FS_40 = FuzzySet(function=Gaussian_MF(-0.812730, 132.556223), term='cluster4')
FS_41 = FuzzySet(function=Gaussian_MF(-1.180703, 249.046111), term='cluster5')
FS_42 = FuzzySet(function=Gaussian_MF(-0.880723, 142.342152), term='cluster6')
MF_x7 = LinguisticVariable([FS_37, FS_38, FS_39, FS_40, FS_41, FS_42], concept='x7' , universe_of_discourse=(-15.557982444763184, 13.196582794189453))
FS.add_linguistic_variable('x7', MF_x7)

FS_43 = FuzzySet(function=Gaussian_MF(-0.024899, 150.503329), term='cluster1')
FS_44 = FuzzySet(function=Gaussian_MF(0.479357, 148.346559), term='cluster2')
FS_45 = FuzzySet(function=Gaussian_MF(0.188231, 201.731085), term='cluster3')
FS_46 = FuzzySet(function=Gaussian_MF(0.507620, 129.545318), term='cluster4')
FS_47 = FuzzySet(function=Gaussian_MF(-0.093089, 232.685916), term='cluster5')
FS_48 = FuzzySet(function=Gaussian_MF(0.250373, 136.576948), term='cluster6')
MF_x8 = LinguisticVariable([FS_43, FS_44, FS_45, FS_46, FS_47, FS_48], concept='x8' , universe_of_discourse=(-13.525594711303711, 14.046455383300781))
FS.add_linguistic_variable('x8', MF_x8)


# end of automatically generated code #